
services:
  web:
    build: ./apache-php
    container_name: lamp_web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    networks:
      - lamp_network
    env_file:
      - .env
    restart: unless-stopped

  db:
    image: mariadb:11
    container_name: lamp_db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - lamp_network


networks:
  lamp_network:
    driver: bridge

volumes:
  db_data:
