[web]
lamp-vm ansible_host=20.91.247.185

[web:vars]
ansible_user=azureadmin
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_private_key_file=/home/rinus/.ssh/id_ed25519
ansible_ssh_common_args='-o IdentitiesOnly=yes'